[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
favourites_program = "CehY6n7M7feYHkt87vnmB21RE9dewFHoWhCAa8h4ZyFs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/signet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
